- name: Copy ryslog conf
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/{{component}}.conf
  when: is_rsyslog_needed

- name: Restart Rsyslog service
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  when: is_rsyslog_needed

- name: Copy Elastic YUM Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install file beat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: Copy filebeat configuration
  ansible.builtin.template:
    src: filebeat
    dest: /etc/filebeat/filebeat.yml

- name: Restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes