- name: Copy filebeat configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  ansible.builtin.systemd_service:
    name: logstash
    state: restarted