- name: Delete Old App Content
  ansible.builtin.file:
    path: /app
    state: absent
- name: Create new directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download and extract backend content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_dir }}"
    remote_src: yes